apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autolog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: online-autolog
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /autolog/db(/|$)(.*)
        backend:
          service:
            name: couchdb
            port:
              number: 5984
