apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: scoring
  name: scoring
  namespace: online-autolog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: scoring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: scoring
    spec:
      containers:
      - image: afiffahreza/online-autolog-scoring:2
        name: scoring
        resources: {}
        env:
          - name: COUCHDB_URL
            value: "http://couchdb-svc-couchdb.online-autolog.svc.cluster.local:5984"
          - name: COUCHDB_USER
            value: "admin"
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: couchdb-couchdb
                key: adminPassword
          - name: LOKI_URL
            value: "http://loki.loki-stack.svc.cluster.local:3100"
          - name: APPLICATIONS
            value: "catalog customer order ingress-nginx"
          - name: TARGET_NUM_BASELINE
            value: "100"
status: {}
