kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pod-failure
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: change-me
  mode: all
  action: pod-failure
  duration: 20s
