apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: default
  name: test-workflow
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 1m
      children:
        - test-workflow-listener
    - name: hit-listener-on
      templateType: Task
      task:
        container:
          image: curlimages/curl
          command:
            - curl
            - '-i'
            - '-s'
            - '-X'
            - POST
            - >-
              http://fault-listener.online-autolog.svc.cluster.local:8000/fault
    - name: test-pod-chaos
      templateType: PodChaos
      deadline: 20s
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: shippingservice
        mode: all
        action: pod-kill
    - name: hit-listener-off
      templateType: Task
      task:
        container:
          image: curlimages/curl
          command:
            - curl
            - '-i'
            - '-s'
            - '-X'
            - POST
            - >-
              http://fault-listener.online-autolog.svc.cluster.local:8000/reset
    - name: test-workflow-listener
      templateType: Serial
      deadline: 1m
      children:
        - hit-listener-on
        - test-pod-chaos
        - hit-listener-off
