apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-1
  namespace: default
spec:
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: checkoutservice
  stressors:
    memory:
      workers: 4
      size: '512MB'
  duration: 10s
