---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: autolog-post-retrain
  name: autolog-post-retrain
  namespace: online-autolog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: autolog-post-retrain
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: autolog-post-retrain
    spec:
      containers:
      - image: afiffahreza/autolog-deployment:6
        name: autolog-post-retrain
        resources:
          limits:
            cpu: 200m
            memory: 640Mi
          requests:
            cpu: 200m
            memory: 512Mi
        env:
          - name: LOKI_URL
            value: "http://loki.loki-stack.svc.cluster.local:3100"
          - name: GCLOUD_SERVICE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: gcp-credentials
                key: gcp-credentials.json
          - name: PREFIX_OUTPUT_DIR
            value: ./post-retrain/
          - name: APPLICATIONS
            value: 'frontend cartservice productcatalogservice currencyservice paymentservice shippingservice emailservice checkoutservice recommendationservice adservice redis-cart'
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: autolog-post-retrain
  name: autolog-post-retrain
  namespace: online-autolog
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: autolog-post-retrain
