---
apiVersion: v1
kind: Namespace
metadata:
  name: online-autolog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: autolog
  name: autolog
  namespace: online-autolog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: autolog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: autolog
    spec:
      containers:
      - image: afiffahreza/autolog-deployment:3
        name: autolog
        resources:
          limits:
            cpu: 300m
            memory: 640Mi
          requests:
            cpu: 300m
            memory: 512Mi
        env:
          - name: ENVIROMENT
            value: "production"
          - name: LOKI_URL
            value: "http://loki.loki-stack.svc.cluster.local:3100"
          - name: GCLOUD_SERVICE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: gcp-credentials
                key: gcp-credentials.json
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: autolog
  name: autolog
  namespace: online-autolog
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: autolog
