---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: fault-listener
  name: fault-listener
  namespace: online-autolog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fault-listener
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: fault-listener
    spec:
      containers:
      - image: afiffahreza/autolog-fault-listener:2
        name: fault-listener
        resources:
          limits:
            cpu: 200m
            memory: 240Mi
          requests:
            cpu: 100m
            memory: 120Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: fault-listener
  name: fault-listener
  namespace: online-autolog
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: autolog
