kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pod-kill-1
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: shippingservice
  mode: all
  action: pod-kill
  duration: 10s
