apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: list
  name: list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: list
    spec:
      containers:
      - image: afiffahreza/list-app:3
        name: list
        ports:
        - containerPort: 8000
        resources: {}
status: {}