apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: error
  name: error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: error
    spec:
      containers:
      - image: afiffahreza/error-app:3
        name: error
        ports:
        - containerPort: 8000
        resources: {}
status: {}